# File: cloudbuild.yaml
steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gpt-chat", "."]
    # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gpt-chat"]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "gpt-chat",
        "--image",
        "gcr.io/$PROJECT_ID/gpt-chat",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--min-instances",
        "0",
        "--max-instances",
        "1",
      ]