# File: cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gpt-chat", "."]
    # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gpt-chat"]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    health_check:
      enable_health_check: False
      check_interval_sec: 60
      timeout_sec: 4
      unhealthy_threshold: 2
      healthy_threshold: 2
    args:
      [
        "run",
        "deploy",
        "gpt-chat",
        "--image",
        "gcr.io/$PROJECT_ID/gpt-chat",
        "--region",
        "europe-central2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        # "--port",
        # "8888",
        "--min-instances",
        "0",
        "--max-instances",
        "1",
      ]